[package]
name = "yawc"
version = "1.0.2"
description = "Yet another Wordle clone"
repository = "https://github.com/zohnannor/wordle/"
readme = "README.md"
license = "MIT"
keywords = ["game", "tui"]
categories = ["games"]
edition = "2024"

[dependencies]
crossterm = "0.29.0"
strip-ansi-escapes = "0.2.1"
rand = "0.9.2"
